namespace SONETWORK
{
	internal enum TradeProto
	{
		PROTO_TRADE_GET_ITEM_LIST = 500,
		PROTO_TRADE_GET_ITEM_LIST_RESULT = 501,
		PROTO_TRADE_GET_ITEM_BY_TYPE_ID = 502,
		PROTO_TRADE_GET_ITEM_BY_TYPE_ID_RESULT = 503,
		PROTO_TRADE_BUY_ITEM = 504,
		PROTO_TRADE_BUY_ITEM_RESULT = 505,
		PROTO_TRADE_SELL_ITEM = 506,
		PROTO_TRADE_SELL_ITEM_RESULT = 507,
		PROTO_TRADE_GET_TREASURE_BOX_ITEM = 508,
		PROTO_TRADE_GET_TREASURE_BOX_ITEM_RESULT = 509,
		PROTO_TRADE_GET_SELF_SELL_ITEM_LIST = 510,
		PROTO_TRADE_GET_SELF_SELL_ITEM_LIST_RESULT = 511,
		PROTO_TRADE_CANCEL_SELF_SELL_ITEM = 512,
		PROTO_TRADE_CANCEL_SELF_SELL_ITEM_RESULT = 513,
		PROTO_TRADE_PLAYER_LOGOUT_CLEAR_DELAY = 514,
		PROTO_TRADE_ADD_SUB_GOLD = 515,
		PROTO_TRADE_ADD_SUB_GOLD_RESULT = 516,
		PROTO_TRADE_SET_SERVER_ID_INFO = 517
	}
}
