public enum Tp2Entry
{
	ENTRY_ID_QZONE = 1,
	ENTRY_ID_MM = 2,
	ENTRT_ID_FACEBOOK = 3,
	ENTRY_ID_TWITTER = 4,
	ENTRY_ID_LINE = 5,
	ENTRY_ID_WHATSAPP = 6,
	ENTRY_ID_GAMECENTER = 7,
	ENTRY_ID_GOOGLEPLAY = 8,
	ENTRY_ID_VK = 9,
	ENTRY_ID_KUAISHOU = 10,
	ENTRY_ID_APPLE = 11,
	ENTRY_ID_NEXON = 12,
	ENTRY_ID_NAVER = 13,
	ENTRY_ID_GARENA = 14,
	ENTRY_ID_HUAWEI = 15,
	ENTRY_ID_OTHERS = 99
}
