public enum WndFormUpdateID
{
	PLAYER_MONEY = 0,
	PLAYER_DIAMOND = 1,
	PLAYER_LEVEL = 2,
	PLAYER_EXP = 3,
	PLAYER_EXPLIMIT = 4,
	PLAYER_FLAGS = 5,
	PLAYER_BATTLE_ITEM = 6,
	PLAYER_AP = 7,
	PLAYER_APMAX = 8,
	PLAYER_APCD = 9,
	PLAYER_APCDMAX = 10,
	PLAYER_TEAM = 11,
	PLAYER_CARESS_NUMBER = 12,
	PLAYER_CARESS_BUY_NUMBER = 13,
	PLAYER_ITEM_BAG_SLOT = 14,
	LOLI_LOVE = 15,
	SERVER_TIME = 16,
	ONLINE_REWARD_TIME = 17,
	HOTKEY_SETTING_CHANGE = 18,
	CASHONLINE_REWARD_TIME = 19
}
