//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ApkValidaterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ApkValidater), typeof(System.Object));
		L.RegFunction("GetData", GetData);
		L.RegFunction("isRooted", isRooted);
		L.RegFunction("IsEmulator", IsEmulator);
		L.RegFunction("isRootedPrivate", isRootedPrivate);
		L.RegFunction("New", _CreateApkValidater);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateApkValidater(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ApkValidater obj = new ApkValidater();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ApkValidater.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = ApkValidater.GetData();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int isRooted(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = ApkValidater.isRooted();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsEmulator(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = ApkValidater.IsEmulator();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int isRootedPrivate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			bool o = ApkValidater.isRootedPrivate(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

