//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AStarMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AStarMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("get_TotalNodes", get_TotalNodes);
		L.RegFunction("get_Instance", get_Instance);
		L.RegFunction("SpawnNodes", SpawnNodes);
		L.RegFunction("Calculate", Calculate);
		L.RegFunction("ClearAutoFindState", ClearAutoFindState);
		L.RegFunction("SGC_CalculateRoute", SGC_CalculateRoute);
		L.RegFunction("SimulateCaculate", SimulateCaculate);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		// HAND-ADDED: production binary (dump.cs TypeDefIndex 319) registers AStarMgrWrap with the
		// same surface as BinFileMgrWrap / ConfigMgrWrap / ResMgrWrap / … — `Instance` is exposed
		// as a Lua property. This AssetRipper-regenerated wrap only emitted the RegFunction
		// `get_Instance` (function-call style); restoring the RegVar binding so
		// `AStarMgr.Instance:SpawnNodes()` (MapInfoMgr.lua:2314) resolves. Uses a SEPARATE
		// property-style getter `_PropertyGet_Instance` to avoid touching the auto-gen body of
		// `get_Instance` (which uses CheckArgsCount(L, 0) — incompatible with tolua's RegVar
		// invocation, which passes the class table as arg 1).
		L.RegVar("Instance", _PropertyGet_Instance, null);
		L.EndClass();
	}

	// HAND-ADDED helper for RegVar("Instance", …). Matches the body of every working singleton
	// wrap's get_Instance (BinFileMgrWrap.cs:50, ConfigMgrWrap.cs:60, ResMgrWrap.cs:50, …) which
	// auto-gen emits when the type is registered with RegVar instead of RegFunction. Kept as a
	// separate function so the AssetRipper-exported get_Instance above stays byte-identical.
	//
	// Note: AStarMgr only exposes the static method `get_Instance()` (Ghidra RVA 0x15AC57C),
	// not a `Instance` property. Calling the method directly preserves the same semantics
	// because tolua only needs the singleton instance to push.
	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _PropertyGet_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, AStarMgr.get_Instance());
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TotalNodes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
			PathNodeRealTime[] o = obj.get_TotalNodes();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			AStarMgr o = AStarMgr.get_Instance();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SpawnNodes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
			obj.SpawnNodes();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Calculate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				PathNodeRealTime[] o = obj.Calculate(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 4)
			{
				AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
				UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				PathNodeRealTime[] o = obj.Calculate(arg0, arg1, arg2);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AStarMgr.Calculate");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAutoFindState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
			obj.ClearAutoFindState();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SGC_CalculateRoute(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			obj.SGC_CalculateRoute(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SimulateCaculate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			AStarMgr obj = (AStarMgr)ToLua.CheckObject<AStarMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			obj.SimulateCaculate(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

