//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AutoSpriteBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AutoSpriteBase), typeof(SpriteBase));
		L.RegFunction("GetDefaultPixelSize", GetDefaultPixelSize);
		L.RegFunction("SetPauseFrame", SetPauseFrame);
		L.RegFunction("GetPauseFrame", GetPauseFrame);
		L.RegFunction("Clear", Clear);
		L.RegFunction("Setup", Setup);
		L.RegFunction("Copy", Copy);
		L.RegFunction("CopyAll", CopyAll);
		L.RegFunction("StepAnim", StepAnim);
		L.RegFunction("PlayAnim", PlayAnim);
		L.RegFunction("PlayAnimInReverse", PlayAnimInReverse);
		L.RegFunction("DoAnim", DoAnim);
		L.RegFunction("SetCurFrame", SetCurFrame);
		L.RegFunction("SetFrame", SetFrame);
		L.RegFunction("StopAnim", StopAnim);
		L.RegFunction("UnpauseAnim", UnpauseAnim);
		L.RegFunction("GetCurAnim", GetCurAnim);
		L.RegFunction("GetAnim", GetAnim);
		L.RegFunction("GetStateIndex", GetStateIndex);
		L.RegFunction("SetState", SetState);
		L.RegFunction("GetPackedMaterial", GetPackedMaterial);
		L.RegFunction("Aggregate", Aggregate);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("doNotTrimImages", get_doNotTrimImages, set_doNotTrimImages);
		L.RegVar("animations", get_animations, set_animations);
		L.RegVar("States", get_States, set_States);
		L.RegVar("DefaultFrame", get_DefaultFrame, null);
		L.RegVar("DefaultState", get_DefaultState, null);
		L.RegVar("SupportsArbitraryAnimations", get_SupportsArbitraryAnimations, null);
		L.RegVar("DoNotTrimImages", get_DoNotTrimImages, set_DoNotTrimImages);
		L.RegVar("SourceTextures", get_SourceTextures, null);
		L.RegVar("SpriteFrames", get_SpriteFrames, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDefaultPixelSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			PathFromGUIDDelegate arg0 = (PathFromGUIDDelegate)ToLua.CheckDelegate<PathFromGUIDDelegate>(L, 2);
			AssetLoaderDelegate arg1 = (AssetLoaderDelegate)ToLua.CheckDelegate<AssetLoaderDelegate>(L, 3);
			UnityEngine.Vector2 o = obj.GetDefaultPixelSize(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPauseFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetPauseFrame(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPauseFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			int o = obj.GetPauseFrame();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Setup(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.Setup(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				UnityEngine.Material arg2 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 4);
				obj.Setup(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AutoSpriteBase.Setup");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Copy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			SpriteRoot arg0 = (SpriteRoot)ToLua.CheckObject<SpriteRoot>(L, 2);
			obj.Copy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyAll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			SpriteRoot arg0 = (SpriteRoot)ToLua.CheckObject<SpriteRoot>(L, 2);
			obj.CopyAll(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StepAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.StepAnim(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAnim(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.PlayAnim(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UVAnimation>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				obj.PlayAnim(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.PlayAnim(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnim(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UVAnimation, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnim(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<string, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnim(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AutoSpriteBase.PlayAnim");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAnimInReverse(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.PlayAnimInReverse(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UVAnimation>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				obj.PlayAnimInReverse(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.PlayAnimInReverse(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnimInReverse(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UVAnimation, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnimInReverse(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<string, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.PlayAnimInReverse(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AutoSpriteBase.PlayAnimInReverse");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DoAnim(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.DoAnim(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.DoAnim(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UVAnimation>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				obj.DoAnim(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AutoSpriteBase.DoAnim");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetCurFrame(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFrame(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<int, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.SetFrame(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<string, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.SetFrame(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UVAnimation, int>(L, 2))
			{
				AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
				UVAnimation arg0 = (UVAnimation)ToLua.ToObject(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				obj.SetFrame(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: AutoSpriteBase.SetFrame");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			obj.StopAnim();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnpauseAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			obj.UnpauseAnim();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			UVAnimation o = obj.GetCurAnim();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UVAnimation o = obj.GetAnim(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStateIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.GetStateIndex(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetState(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPackedMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			string arg0 = null;
			UnityEngine.Material o = obj.GetPackedMaterial(out arg0);
			ToLua.Push(L, o);
			LuaDLL.lua_pushstring(L, arg0);
			return 2;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Aggregate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			AutoSpriteBase obj = (AutoSpriteBase)ToLua.CheckObject<AutoSpriteBase>(L, 1);
			PathFromGUIDDelegate arg0 = (PathFromGUIDDelegate)ToLua.CheckDelegate<PathFromGUIDDelegate>(L, 2);
			LoadAssetDelegate arg1 = (LoadAssetDelegate)ToLua.CheckDelegate<LoadAssetDelegate>(L, 3);
			GUIDFromPathDelegate arg2 = (GUIDFromPathDelegate)ToLua.CheckDelegate<GUIDFromPathDelegate>(L, 4);
			obj.Aggregate(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_doNotTrimImages(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			bool ret = obj.doNotTrimImages;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doNotTrimImages on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_animations(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			UVAnimation[] ret = obj.animations;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animations on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_States(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			TextureAnim[] ret = obj.States;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index States on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultFrame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			CSpriteFrame ret = obj.DefaultFrame;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultFrame on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			TextureAnim ret = obj.DefaultState;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DefaultState on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SupportsArbitraryAnimations(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			bool ret = obj.SupportsArbitraryAnimations;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SupportsArbitraryAnimations on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DoNotTrimImages(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			bool ret = obj.DoNotTrimImages;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DoNotTrimImages on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SourceTextures(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			UnityEngine.Texture2D[] ret = obj.SourceTextures;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SourceTextures on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SpriteFrames(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			CSpriteFrame[] ret = obj.SpriteFrames;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SpriteFrames on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_doNotTrimImages(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.doNotTrimImages = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doNotTrimImages on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_animations(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			UVAnimation[] arg0 = ToLua.CheckObjectArray<UVAnimation>(L, 2);
			obj.animations = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index animations on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_States(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			TextureAnim[] arg0 = ToLua.CheckObjectArray<TextureAnim>(L, 2);
			obj.States = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index States on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_DoNotTrimImages(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AutoSpriteBase obj = (AutoSpriteBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.DoNotTrimImages = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DoNotTrimImages on a nil value");
		}
	}
}

