//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BinFileMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BinFileMgr), typeof(System.Object));
		L.RegFunction("getEveData", getEveData);
		L.RegFunction("setEveData", setEveData);
		L.RegFunction("newLevel", newLevel);
		L.RegFunction("loadLevel", loadLevel);
		L.RegFunction("printData", printData);
		L.RegFunction("printToFile", printToFile);
		L.RegFunction("writeToFile", writeToFile);
		L.RegFunction("clean", clean);
		L.RegFunction("New", _CreateBinFileMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("binData", get_binData, set_binData);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateBinFileMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				BinFileMgr obj = new BinFileMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: BinFileMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getEveData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			tageventDATA[] o = obj.getEveData();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setEveData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			System.Collections.Generic.List<tageventDATA> arg0 = (System.Collections.Generic.List<tageventDATA>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<tageventDATA>));
			obj.setEveData(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int newLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.newLevel(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int loadLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.loadLevel(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int printData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			obj.printData();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int printToFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			obj.printToFile();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int writeToFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			obj.writeToFile();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int clean(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			BinFileMgr obj = (BinFileMgr)ToLua.CheckObject<BinFileMgr>(L, 1);
			obj.clean();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, BinFileMgr.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_binData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BinFileMgr obj = (BinFileMgr)o;
			BinData ret = obj.binData;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index binData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_binData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			BinFileMgr obj = (BinFileMgr)o;
			BinData arg0 = (BinData)ToLua.CheckObject<BinData>(L, 2);
			obj.binData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index binData on a nil value");
		}
	}
}

