//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ConfigVarWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ConfigVar), typeof(System.Object));
		L.RegFunction("New", _CreateConfigVar);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("SelectServer", 1);
		L.RegConstant("LoginAccount", 2);
		L.RegConstant("Login_Account", 3);
		L.RegConstant("Login_Pwd", 4);
		L.RegConstant("UserBGM", 5);
		L.RegConstant("UserSE", 6);
		L.RegConstant("TestBGM", 7);
		L.RegConstant("TestSE", 8);
		L.RegConstant("Notification", 9);
		L.RegConstant("ClearCache", 10);
		L.RegConstant("CachedBundleHash", 11);
		L.RegConstant("SGCLanguage", 12);
		L.RegConstant("SGCRegion", 13);
		L.RegConstant("SelectServer2", 14);
		L.RegConstant("PermissionDenied", 15);
		L.RegConstant("FullScreen", 16);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateConfigVar(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ConfigVar obj = new ConfigVar();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ConfigVar.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

