//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CProcManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CProcManager), typeof(System.Object));
		L.RegFunction("Start", Start);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("OnApplicationQuit", OnApplicationQuit);
		L.RegFunction("SwitchProc", SwitchProc);
		L.RegFunction("PushProc", PushProc);
		L.RegFunction("PopProc", PopProc);
		L.RegFunction("Update", Update);
		L.RegFunction("FixedUpdate", FixedUpdate);
		L.RegFunction("LateUpdate", LateUpdate);
		L.RegFunction("New", _CreateCProcManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("cbSwitchEventFunc", get_cbSwitchEventFunc, set_cbSwitchEventFunc);
		L.RegVar("eCurProcID", get_eCurProcID, null);
		L.RegVar("curProc", get_curProc, null);
		L.RegFunction("CBSwitchEventFunc", CProcManager_CBSwitchEventFunc);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCProcManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CProcManager obj = new CProcManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CProcManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				obj.Start();
				return 0;
			}
			else if (count == 2)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				System.Collections.ArrayList arg0 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 2);
				obj.Start(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CProcManager.Start");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
			obj.Destroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnApplicationQuit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
			obj.OnApplicationQuit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SwitchProc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				obj.SwitchProc(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<bool>(L, 3))
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				obj.SwitchProc(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<System.Collections.ArrayList>(L, 3))
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.ToObject(L, 3);
				obj.SwitchProc(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.SwitchProc(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CProcManager.SwitchProc");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PushProc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				obj.PushProc(arg0);
				return 0;
			}
			else if (count == 3)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				EProcID arg0 = (EProcID)ToLua.CheckObject(L, 2, typeof(EProcID));
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				obj.PushProc(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CProcManager.PushProc");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PopProc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				obj.PopProc();
				return 0;
			}
			else if (count == 2)
			{
				CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
				System.Collections.ArrayList arg0 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 2);
				obj.PopProc(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: CProcManager.PopProc");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FixedUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
			obj.FixedUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LateUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CProcManager obj = (CProcManager)ToLua.CheckObject<CProcManager>(L, 1);
			obj.LateUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cbSwitchEventFunc(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			CProcManager obj = (CProcManager)o;
			CProcManager.CBSwitchEventFunc ret = obj.cbSwitchEventFunc;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cbSwitchEventFunc on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eCurProcID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			CProcManager obj = (CProcManager)o;
			EProcID ret = obj.eCurProcID;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eCurProcID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curProc(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			CProcManager obj = (CProcManager)o;
			CBaseProc ret = obj.curProc;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curProc on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cbSwitchEventFunc(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			CProcManager obj = (CProcManager)o;
			CProcManager.CBSwitchEventFunc arg0 = (CProcManager.CBSwitchEventFunc)ToLua.CheckDelegate<CProcManager.CBSwitchEventFunc>(L, 2);
			obj.cbSwitchEventFunc = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cbSwitchEventFunc on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CProcManager_CBSwitchEventFunc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<CProcManager.CBSwitchEventFunc>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<CProcManager.CBSwitchEventFunc>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

