//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CreateJobIMGWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CreateJobIMG), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("setSprite", setSprite);
		L.RegFunction("setHeadIcon", setHeadIcon);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Ins", get_Ins, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setSprite(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CreateJobIMG obj = (CreateJobIMG)ToLua.CheckObject<CreateJobIMG>(L, 1);
			UnityEngine.UI.Image arg0 = (UnityEngine.UI.Image)ToLua.CheckObject<UnityEngine.UI.Image>(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.setSprite(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setHeadIcon(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CreateJobIMG obj = (CreateJobIMG)ToLua.CheckObject<CreateJobIMG>(L, 1);
			UnityEngine.UI.Image arg0 = (UnityEngine.UI.Image)ToLua.CheckObject<UnityEngine.UI.Image>(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.setHeadIcon(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Ins(IntPtr L)
	{
		try
		{
			ToLua.Push(L, CreateJobIMG.Ins);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

