//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FxhySDKManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FxhySDKManager), typeof(System.Object));
		L.RegFunction("SetPlayerId", SetPlayerId);
		L.RegFunction("GetPlayerId", GetPlayerId);
		L.RegFunction("HasInfoForLogin", HasInfoForLogin);
		L.RegFunction("GetGameRegionName", GetGameRegionName);
		L.RegFunction("GetAgreePersonalInfoGuideStatus", GetAgreePersonalInfoGuideStatus);
		L.RegFunction("GetShowingPersonalInfoGuideStatus", GetShowingPersonalInfoGuideStatus);
		L.RegFunction("GetInitSdkDone", GetInitSdkDone);
		L.RegFunction("ShowPersonalInfoGuideDialog", ShowPersonalInfoGuideDialog);
		L.RegFunction("InitSDK", InitSDK);
		L.RegFunction("IsLogin", IsLogin);
		L.RegFunction("CheckLogin", CheckLogin);
		L.RegFunction("StartLogin", StartLogin);
		L.RegFunction("StartLogout", StartLogout);
		L.RegFunction("StartUserCenter", StartUserCenter);
		L.RegFunction("ShowCloseAccount", ShowCloseAccount);
		L.RegFunction("ShowRealNameAuthentication", ShowRealNameAuthentication);
		L.RegFunction("ShowRoundIdentityInfo", ShowRoundIdentityInfo);
		L.RegFunction("ShowWebDialog", ShowWebDialog);
		L.RegFunction("ShowWebUIDialog", ShowWebUIDialog);
		L.RegFunction("ShowWebSystem", ShowWebSystem);
		L.RegFunction("UploadGameUserInfo", UploadGameUserInfo);
		L.RegFunction("CreateOrderAndPay", CreateOrderAndPay);
		L.RegFunction("GetGameRegionNameFromSdk", GetGameRegionNameFromSdk);
		L.RegFunction("GetCheckForbiddenWordSign", GetCheckForbiddenWordSign);
		L.RegFunction("SetTestEnvironment", SetTestEnvironment);
		L.RegFunction("New", _CreateFxhySDKManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("FXHYSDK_PLAYER_ID", get_FXHYSDK_PLAYER_ID, null);
		L.RegVar("FXHYSDK_AGREE_STATUS", get_FXHYSDK_AGREE_STATUS, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFxhySDKManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FxhySDKManager obj = new FxhySDKManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FxhySDKManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPlayerId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			FxhySDKManager.SetPlayerId(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPlayerId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = FxhySDKManager.GetPlayerId();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasInfoForLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = FxhySDKManager.HasInfoForLogin();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGameRegionName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string o = FxhySDKManager.GetGameRegionName();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAgreePersonalInfoGuideStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = FxhySDKManager.GetAgreePersonalInfoGuideStatus();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetShowingPersonalInfoGuideStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = FxhySDKManager.GetShowingPersonalInfoGuideStatus();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInitSdkDone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = FxhySDKManager.GetInitSdkDone();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowPersonalInfoGuideDialog(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.ShowPersonalInfoGuideDialog();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitSDK(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.InitSDK();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = FxhySDKManager.IsLogin();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CheckLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.CheckLogin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.StartLogin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartLogout(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.StartLogout();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartUserCenter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.StartUserCenter();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowCloseAccount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.ShowCloseAccount();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowRealNameAuthentication(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.ShowRealNameAuthentication();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowRoundIdentityInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			FxhySDKManager.ShowRoundIdentityInfo();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowWebDialog(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			FxhySDKManager.ShowWebDialog(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowWebUIDialog(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			FxhySDKManager.ShowWebUIDialog(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowWebSystem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			FxhySDKManager.ShowWebSystem(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UploadGameUserInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			string arg3 = ToLua.CheckString(L, 4);
			FxhySDKManager.UploadGameUserInfo(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateOrderAndPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 10);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			string arg3 = ToLua.CheckString(L, 4);
			string arg4 = ToLua.CheckString(L, 5);
			string arg5 = ToLua.CheckString(L, 6);
			string arg6 = ToLua.CheckString(L, 7);
			string arg7 = ToLua.CheckString(L, 8);
			string arg8 = ToLua.CheckString(L, 9);
			string arg9 = ToLua.CheckString(L, 10);
			FxhySDKManager.CreateOrderAndPay(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGameRegionNameFromSdk(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			string[] o = FxhySDKManager.GetGameRegionNameFromSdk();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCheckForbiddenWordSign(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = FxhySDKManager.GetCheckForbiddenWordSign(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTestEnvironment(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			FxhySDKManager.SetTestEnvironment(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FXHYSDK_PLAYER_ID(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FxhySDKManager.FXHYSDK_PLAYER_ID);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FXHYSDK_AGREE_STATUS(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FxhySDKManager.FXHYSDK_AGREE_STATUS);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

