//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class InfiniteScrollWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(InfiniteScroll), typeof(UnityEngine.UI.ScrollRect));
		L.RegFunction("ResetByIndex", ResetByIndex);
		L.RegFunction("Reset", Reset);
		L.RegFunction("_Reset", _Reset);
		L.RegFunction("OnBeginDrag", OnBeginDrag);
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("prefabItem", get_prefabItem, set_prefabItem);
		L.RegVar("_pool", get__pool, set__pool);
		L.RegVar("OnUpdateData", get_OnUpdateData, set_OnUpdateData);
		L.RegVar("OnRemove", get_OnRemove, set_OnRemove);
		L.RegVar("MaxCount", get_MaxCount, set_MaxCount);
		L.RegFunction("InfiniteScrollRemoveEvent", InfiniteScroll_InfiniteScrollRemoveEvent);
		L.RegFunction("InfiniteScrollUpdateEvent", InfiniteScroll_InfiniteScrollUpdateEvent);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetByIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			InfiniteScroll obj = (InfiniteScroll)ToLua.CheckObject<InfiniteScroll>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.ResetByIndex(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			InfiniteScroll obj = (InfiniteScroll)ToLua.CheckObject<InfiniteScroll>(L, 1);
			obj.Reset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			InfiniteScroll obj = (InfiniteScroll)ToLua.CheckObject<InfiniteScroll>(L, 1);
			obj._Reset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBeginDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			InfiniteScroll obj = (InfiniteScroll)ToLua.CheckObject<InfiniteScroll>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnBeginDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			InfiniteScroll obj = (InfiniteScroll)ToLua.CheckObject<InfiniteScroll>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_prefabItem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			UnityEngine.RectTransform ret = obj.prefabItem;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index prefabItem on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__pool(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			System.Collections.Generic.List<UnityEngine.RectTransform> ret = obj._pool;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _pool on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnUpdateData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			InfiniteScroll.InfiniteScrollUpdateEvent ret = obj.OnUpdateData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnUpdateData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnRemove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			InfiniteScroll.InfiniteScrollRemoveEvent ret = obj.OnRemove;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnRemove on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MaxCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			int ret = obj.MaxCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MaxCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_prefabItem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			UnityEngine.RectTransform arg0 = (UnityEngine.RectTransform)ToLua.CheckObject(L, 2, typeof(UnityEngine.RectTransform));
			obj.prefabItem = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index prefabItem on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__pool(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			System.Collections.Generic.List<UnityEngine.RectTransform> arg0 = (System.Collections.Generic.List<UnityEngine.RectTransform>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<UnityEngine.RectTransform>));
			obj._pool = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _pool on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnUpdateData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			InfiniteScroll.InfiniteScrollUpdateEvent arg0 = (InfiniteScroll.InfiniteScrollUpdateEvent)ToLua.CheckDelegate<InfiniteScroll.InfiniteScrollUpdateEvent>(L, 2);
			obj.OnUpdateData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnUpdateData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnRemove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			InfiniteScroll.InfiniteScrollRemoveEvent arg0 = (InfiniteScroll.InfiniteScrollRemoveEvent)ToLua.CheckDelegate<InfiniteScroll.InfiniteScrollRemoveEvent>(L, 2);
			obj.OnRemove = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OnRemove on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MaxCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			InfiniteScroll obj = (InfiniteScroll)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.MaxCount = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MaxCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InfiniteScroll_InfiniteScrollRemoveEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<InfiniteScroll.InfiniteScrollRemoveEvent>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<InfiniteScroll.InfiniteScrollRemoveEvent>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InfiniteScroll_InfiniteScrollUpdateEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<InfiniteScroll.InfiniteScrollUpdateEvent>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<InfiniteScroll.InfiniteScrollUpdateEvent>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

