//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class IWndComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(IWndComponent), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("InitComponent", InitComponent);
		L.RegFunction("DinitComponent", DinitComponent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			IWndComponent obj = (IWndComponent)ToLua.CheckObject<IWndComponent>(L, 1);
			WndForm arg0 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			obj.InitComponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DinitComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			IWndComponent obj = (IWndComponent)ToLua.CheckObject<IWndComponent>(L, 1);
			WndForm arg0 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			obj.DinitComponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

