//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MagicFxData_FxDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MagicFxData.FxData), typeof(System.Object));
		L.RegFunction("New", _CreateMagicFxData_FxData);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("fxName", get_fxName, set_fxName);
		L.RegVar("soundName", get_soundName, set_soundName);
		L.RegVar("soundName2", get_soundName2, set_soundName2);
		L.RegVar("mode", get_mode, set_mode);
		L.RegVar("part", get_part, set_part);
		L.RegVar("offset", get_offset, set_offset);
		L.RegVar("part2", get_part2, set_part2);
		L.RegVar("offset2", get_offset2, set_offset2);
		L.RegVar("faceMode", get_faceMode, set_faceMode);
		L.RegVar("rotationY", get_rotationY, set_rotationY);
		L.RegVar("timeDelay", get_timeDelay, set_timeDelay);
		L.RegVar("speedDelay", get_speedDelay, set_speedDelay);
		L.RegVar("timeMode", get_timeMode, set_timeMode);
		L.RegVar("timeTotal", get_timeTotal, set_timeTotal);
		L.RegVar("doAction", get_doAction, set_doAction);
		L.RegVar("doActionTime", get_doActionTime, set_doActionTime);
		L.RegVar("enableCameraShake", get_enableCameraShake, set_enableCameraShake);
		L.RegVar("cameraShakeNum", get_cameraShakeNum, set_cameraShakeNum);
		L.RegVar("cameraShakePos", get_cameraShakePos, set_cameraShakePos);
		L.RegVar("cameraShakeFrequency", get_cameraShakeFrequency, set_cameraShakeFrequency);
		L.RegVar("cameraShakeDecrease", get_cameraShakeDecrease, set_cameraShakeDecrease);
		L.RegVar("cameraShakeEveryOne", get_cameraShakeEveryOne, set_cameraShakeEveryOne);
		L.RegVar("cameraShakeDistanceX", get_cameraShakeDistanceX, set_cameraShakeDistanceX);
		L.RegVar("enableCameraFOV", get_enableCameraFOV, set_enableCameraFOV);
		L.RegVar("cameraFOVTime", get_cameraFOVTime, set_cameraFOVTime);
		L.RegVar("cameraFOVValue", get_cameraFOVValue, set_cameraFOVValue);
		L.RegVar("cameraFOVFadeInTime", get_cameraFOVFadeInTime, set_cameraFOVFadeInTime);
		L.RegVar("cameraFOVFadeOutTime", get_cameraFOVFadeOutTime, set_cameraFOVFadeOutTime);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMagicFxData_FxData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MagicFxData.FxData obj = new MagicFxData.FxData();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MagicFxData.FxData.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fxName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string ret = obj.fxName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index fxName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_soundName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string ret = obj.soundName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index soundName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_soundName2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string ret = obj.soundName2;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index soundName2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.mode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_part(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.part;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index part on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 ret = obj.offset;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index offset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_part2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.part2;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index part2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_offset2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 ret = obj.offset2;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index offset2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_faceMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.faceMode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index faceMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rotationY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.rotationY;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rotationY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_timeDelay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.timeDelay;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeDelay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_speedDelay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.speedDelay;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speedDelay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_timeMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.timeMode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_timeTotal(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.timeTotal;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeTotal on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_doAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.doAction;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_doActionTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.doActionTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doActionTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_enableCameraShake(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool ret = obj.enableCameraShake;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enableCameraShake on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakeNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int ret = obj.cameraShakeNum;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeNum on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakePos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 ret = obj.cameraShakePos;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakePos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakeFrequency(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraShakeFrequency;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeFrequency on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakeDecrease(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraShakeDecrease;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeDecrease on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakeEveryOne(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool ret = obj.cameraShakeEveryOne;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeEveryOne on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraShakeDistanceX(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraShakeDistanceX;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeDistanceX on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_enableCameraFOV(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool ret = obj.enableCameraFOV;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enableCameraFOV on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraFOVTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraFOVTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraFOVValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraFOVValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraFOVFadeInTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraFOVFadeInTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVFadeInTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraFOVFadeOutTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float ret = obj.cameraFOVFadeOutTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVFadeOutTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_fxName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.fxName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index fxName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_soundName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.soundName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index soundName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_soundName2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.soundName2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index soundName2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.mode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_part(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.part = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index part on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.offset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index offset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_part2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.part2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index part2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_offset2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.offset2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index offset2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_faceMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.faceMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index faceMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_rotationY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.rotationY = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rotationY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_timeDelay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.timeDelay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeDelay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_speedDelay(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.speedDelay = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index speedDelay on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_timeMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.timeMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_timeTotal(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.timeTotal = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeTotal on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_doAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.doAction = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_doActionTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.doActionTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index doActionTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_enableCameraShake(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.enableCameraShake = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enableCameraShake on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakeNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraShakeNum = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeNum on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakePos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			obj.cameraShakePos = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakePos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakeFrequency(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraShakeFrequency = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeFrequency on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakeDecrease(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraShakeDecrease = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeDecrease on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakeEveryOne(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.cameraShakeEveryOne = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeEveryOne on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraShakeDistanceX(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraShakeDistanceX = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraShakeDistanceX on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_enableCameraFOV(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.enableCameraFOV = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enableCameraFOV on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraFOVTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraFOVTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraFOVValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraFOVValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraFOVFadeInTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraFOVFadeInTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVFadeInTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraFOVFadeOutTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxData obj = (MagicFxData.FxData)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraFOVFadeOutTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraFOVFadeOutTime on a nil value");
		}
	}
}

