//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MagicFxData_FxDatasWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MagicFxData.FxDatas), typeof(System.Object));
		L.RegFunction("ResetTimeTotal", ResetTimeTotal);
		L.RegFunction("New", _CreateMagicFxData_FxDatas);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("data", get_data, set_data);
		L.RegVar("timeTotal", get_timeTotal, set_timeTotal);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMagicFxData_FxDatas(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MagicFxData.FxDatas obj = new MagicFxData.FxDatas();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MagicFxData.FxDatas.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetTimeTotal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MagicFxData.FxDatas obj = (MagicFxData.FxDatas)ToLua.CheckObject<MagicFxData.FxDatas>(L, 1);
			obj.ResetTimeTotal();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxDatas obj = (MagicFxData.FxDatas)o;
			System.Collections.Generic.List<MagicFxData.FxData> ret = obj.data;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_timeTotal(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxDatas obj = (MagicFxData.FxDatas)o;
			float ret = obj.timeTotal;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeTotal on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxDatas obj = (MagicFxData.FxDatas)o;
			System.Collections.Generic.List<MagicFxData.FxData> arg0 = (System.Collections.Generic.List<MagicFxData.FxData>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<MagicFxData.FxData>));
			obj.data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_timeTotal(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxData.FxDatas obj = (MagicFxData.FxDatas)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.timeTotal = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index timeTotal on a nil value");
		}
	}
}

