//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MagicFxLoader_FxLoaderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MagicFxLoader.FxLoader), typeof(System.Object));
		L.RegFunction("New", _CreateMagicFxLoader_FxLoader);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("resObj", get_resObj, set_resObj);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMagicFxLoader_FxLoader(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MagicFxLoader.FxLoader obj = new MagicFxLoader.FxLoader();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MagicFxLoader.FxLoader.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_resObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxLoader.FxLoader obj = (MagicFxLoader.FxLoader)o;
			FxResource ret = obj.resObj;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index resObj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_resObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxLoader.FxLoader obj = (MagicFxLoader.FxLoader)o;
			FxResource arg0 = (FxResource)ToLua.CheckObject<FxResource>(L, 2);
			obj.resObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index resObj on a nil value");
		}
	}
}

