//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MagicFxLoader_FxLoadersWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MagicFxLoader.FxLoaders), typeof(System.Object));
		L.RegFunction("New", _CreateMagicFxLoader_FxLoaders);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("data", get_data, set_data);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMagicFxLoader_FxLoaders(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MagicFxLoader.FxLoaders obj = new MagicFxLoader.FxLoaders();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MagicFxLoader.FxLoaders.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxLoader.FxLoaders obj = (MagicFxLoader.FxLoaders)o;
			System.Collections.Generic.List<MagicFxLoader.FxLoader> ret = obj.data;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MagicFxLoader.FxLoaders obj = (MagicFxLoader.FxLoaders)o;
			System.Collections.Generic.List<MagicFxLoader.FxLoader> arg0 = (System.Collections.Generic.List<MagicFxLoader.FxLoader>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<MagicFxLoader.FxLoader>));
			obj.data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}
}

