//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MarsSDK_MarsFunction_DeleteAccountActionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MarsSDK.MarsFunction.DeleteAccountAction), typeof(System.Object));
		L.RegFunction("IsWaitingToReset", IsWaitingToReset);
		L.RegFunction("GetRestoreTimestamp", GetRestoreTimestamp);
		L.RegFunction("RequestDeleteAccount", RequestDeleteAccount);
		L.RegFunction("RequestRestoreAccount", RequestRestoreAccount);
		L.RegFunction("ShowMarsDeleteAccountUI", ShowMarsDeleteAccountUI);
		L.RegFunction("ShowMarsRestoreAccountUI", ShowMarsRestoreAccountUI);
		L.RegFunction("New", _CreateMarsSDK_MarsFunction_DeleteAccountAction);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMarsSDK_MarsFunction_DeleteAccountAction(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MarsSDK.MarsFunction.DeleteAccountAction obj = new MarsSDK.MarsFunction.DeleteAccountAction();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MarsSDK.MarsFunction.DeleteAccountAction.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsWaitingToReset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = MarsSDK.MarsFunction.DeleteAccountAction.IsWaitingToReset();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRestoreTimestamp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			long o = MarsSDK.MarsFunction.DeleteAccountAction.GetRestoreTimestamp();
			LuaDLL.tolua_pushint64(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RequestDeleteAccount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MarsSDK.MarsFunction.DeleteAccountAction.RequestDeleteAccount();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RequestRestoreAccount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MarsSDK.MarsFunction.DeleteAccountAction.RequestRestoreAccount();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowMarsDeleteAccountUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MarsSDK.MarsFunction.DeleteAccountAction.ShowMarsDeleteAccountUI();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowMarsRestoreAccountUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MarsSDK.MarsFunction.DeleteAccountAction.ShowMarsRestoreAccountUI();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

