//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MarsSDK_MarsMessageProcessWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MarsSDK.MarsMessageProcess), typeof(System.Object));
		L.RegFunction("GetMessageUserType", GetMessageUserType);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("AgentId", get_AgentId, set_AgentId);
		L.RegVar("PlatformDefinition", get_PlatformDefinition, set_PlatformDefinition);
		L.RegVar("ExtensionDefinition", get_ExtensionDefinition, set_ExtensionDefinition);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMessageUserType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)ToLua.CheckObject<MarsSDK.MarsMessageProcess>(L, 1);
			System.Type o = obj.GetMessageUserType();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AgentId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsSDK.EOperationAgent ret = obj.AgentId;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AgentId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlatformDefinition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsAgent.Login.PlatformDefinition ret = obj.PlatformDefinition;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PlatformDefinition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExtensionDefinition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsSDK.ThirdParty.Extensions.ExtensionDefinition ret = obj.ExtensionDefinition;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ExtensionDefinition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AgentId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsSDK.EOperationAgent arg0 = (MarsSDK.EOperationAgent)ToLua.CheckObject(L, 2, typeof(MarsSDK.EOperationAgent));
			obj.AgentId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AgentId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_PlatformDefinition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsAgent.Login.PlatformDefinition arg0 = (MarsAgent.Login.PlatformDefinition)ToLua.CheckObject(L, 2, typeof(MarsAgent.Login.PlatformDefinition));
			obj.PlatformDefinition = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PlatformDefinition on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ExtensionDefinition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MarsSDK.MarsMessageProcess obj = (MarsSDK.MarsMessageProcess)o;
			MarsSDK.ThirdParty.Extensions.ExtensionDefinition arg0 = (MarsSDK.ThirdParty.Extensions.ExtensionDefinition)ToLua.CheckObject(L, 2, typeof(MarsSDK.ThirdParty.Extensions.ExtensionDefinition));
			obj.ExtensionDefinition = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ExtensionDefinition on a nil value");
		}
	}
}

