//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;
using Object = UnityEngine.Object;

public class MusicProxyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MusicProxy), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("get_main", get_main);
		L.RegFunction("get_masterVolume", get_masterVolume);
		L.RegFunction("set_masterVolume", set_masterVolume);
		L.RegFunction("Save", Save);
		L.RegFunction("Play", Play);
		L.RegFunction("Stop", Stop);
		L.RegFunction("get_musicMask", get_musicMask);
		L.RegFunction("OnMusicLoaded", OnMusicLoaded);
		L.RegFunction("PlayPreMusic", PlayPreMusic);
		L.RegFunction("SetMute", SetMute);
		L.RegFunction("ClearCache", ClearCache);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("CMinVolume", 0);
		L.RegConstant("CMaxVoulume", 1);
		L.RegVar("_isMain", get__isMain, set__isMain);
		L.RegVar("_CachedAudio", get__CachedAudio, set__CachedAudio);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_main(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			MusicProxy o = MusicProxy.get_main();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_masterVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			float o = MusicProxy.get_masterVolume();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_masterVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			MusicProxy.set_masterVolume(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Save(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			MusicProxy.Save(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AudioClip>(L, 2))
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.ToObject(L, 2);
				bool o = obj.Play(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				string arg0 = ToLua.ToString(L, 2);
				bool o = obj.Play(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool o = obj.Play(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 4)
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				AssetBundleOP arg2 = (AssetBundleOP)ToLua.CheckObject(L, 4, typeof(AssetBundleOP));
				bool o = obj.Play(arg0, arg1, arg2);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MusicProxy.Play");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Stop(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				obj.Stop();
				return 0;
			}
			else if (count == 2)
			{
				MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				obj.Stop(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MusicProxy.Stop");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_musicMask(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
			uint o = obj.get_musicMask();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnMusicLoaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
			UnityEngine.Object[] arg0 = ToLua.CheckObjectArray<UnityEngine.Object>(L, 2);
			obj.OnMusicLoaded(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayPreMusic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.PlayPreMusic(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMute(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetMute(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MusicProxy obj = (MusicProxy)ToLua.CheckObject(L, 1, typeof(MusicProxy));
			obj.ClearCache();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__isMain(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MusicProxy obj = (MusicProxy)o;
			bool ret = obj._isMain;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _isMain on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__CachedAudio(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MusicProxy obj = (MusicProxy)o;
			System.Collections.Generic.Dictionary<string,AudioClipCache> ret = obj._CachedAudio;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _CachedAudio on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__isMain(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MusicProxy obj = (MusicProxy)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj._isMain = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _isMain on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__CachedAudio(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MusicProxy obj = (MusicProxy)o;
			System.Collections.Generic.Dictionary<string,AudioClipCache> arg0 = (System.Collections.Generic.Dictionary<string,AudioClipCache>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,AudioClipCache>));
			obj._CachedAudio = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _CachedAudio on a nil value");
		}
	}
}

