//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetReceivePackerBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NetReceivePackerBase), typeof(System.Object));
		L.RegFunction("readInt32", readInt32);
		L.RegFunction("readInt64", readInt64);
		L.RegFunction("readUInt32", readUInt32);
		L.RegFunction("readUInt64", readUInt64);
		L.RegFunction("readInt16", readInt16);
		L.RegFunction("readUInt16", readUInt16);
		L.RegFunction("readFloat", readFloat);
		L.RegFunction("readDouble", readDouble);
		L.RegFunction("readByte", readByte);
		L.RegFunction("readSByte", readSByte);
		L.RegFunction("readStringLen", readStringLen);
		L.RegFunction("readString", readString);
		L.RegFunction("readBytes", readBytes);
		L.RegFunction("getStartIndex", getStartIndex);
		L.RegFunction("setStartIndex", setStartIndex);
		L.RegFunction("getData", getData);
		L.RegFunction("New", _CreateNetReceivePackerBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetReceivePackerBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
				NetReceivePackerBase obj = new NetReceivePackerBase(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NetReceivePackerBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readInt32(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int o = obj.readInt32();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readInt64(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			long o = obj.readInt64();
			LuaDLL.tolua_pushint64(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readUInt32(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			uint o = obj.readUInt32();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readUInt64(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			ulong o = obj.readUInt64();
			LuaDLL.tolua_pushuint64(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readInt16(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			short o = obj.readInt16();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readUInt16(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			ushort o = obj.readUInt16();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readFloat(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			float o = obj.readFloat();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readDouble(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			double o = obj.readDouble();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readByte(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			byte o = obj.readByte();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readSByte(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			sbyte o = obj.readSByte();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readStringLen(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int o = obj.readStringLen();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string o = obj.readString(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int readBytes(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			byte[] o = obj.readBytes(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getStartIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int o = obj.getStartIndex();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setStartIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.setStartIndex(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceivePackerBase obj = (NetReceivePackerBase)ToLua.CheckObject<NetReceivePackerBase>(L, 1);
			byte[] o = obj.getData();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

