//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetReceiverLuaWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NetReceiverLua), typeof(System.Object));
		L.RegFunction("SetCbNetReceiverLua", SetCbNetReceiverLua);
		L.RegFunction("CallInit", CallInit);
		L.RegFunction("SetNetCallbackFuncLua", SetNetCallbackFuncLua);
		L.RegFunction("OnNetCallbackFunc", OnNetCallbackFunc);
		L.RegFunction("OnServerConnected", OnServerConnected);
		L.RegFunction("OnServerDisconnect", OnServerDisconnect);
		L.RegFunction("New", _CreateNetReceiverLua);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("LuaClass", get_LuaClass, set_LuaClass);
		L.RegVar("LuaClassObj", get_LuaClassObj, set_LuaClassObj);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetReceiverLua(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				NetReceiverLua obj = new NetReceiverLua();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NetReceiverLua.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCbNetReceiverLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			object arg1 = ToLua.ToVarObject(L, 2);
			NetReceiverLua.SetCbNetReceiverLua(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetReceiverLua obj = (NetReceiverLua)ToLua.CheckObject<NetReceiverLua>(L, 1);
			obj.CallInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetNetCallbackFuncLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			NetReceiverLua.SetNetCallbackFuncLua(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnNetCallbackFunc(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<byte[]>(L, 2))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				byte[] arg1 = ToLua.CheckByteBuffer(L, 2);
				NetReceiverLua.OnNetCallbackFunc(arg0, arg1);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<NetReceivePackerBase>(L, 2))
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				NetReceivePackerBase arg1 = (NetReceivePackerBase)ToLua.ToObject(L, 2);
				NetReceiverLua.OnNetCallbackFunc(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: NetReceiverLua.OnNetCallbackFunc");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnServerConnected(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			NetReceiverLua.OnServerConnected();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnServerDisconnect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			NetReceiverLua.OnServerDisconnect(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, NetReceiverLua.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClass(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetReceiverLua obj = (NetReceiverLua)o;
			string ret = obj.LuaClass;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClass on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaClassObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetReceiverLua obj = (NetReceiverLua)o;
			object ret = obj.LuaClassObj;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClassObj on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClass(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetReceiverLua obj = (NetReceiverLua)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.LuaClass = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClass on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaClassObj(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetReceiverLua obj = (NetReceiverLua)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.LuaClassObj = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaClassObj on a nil value");
		}
	}
}

