//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PathNodeRealTimeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PathNodeRealTime), typeof(System.Object));
		L.RegFunction("get_parent", get_parent);
		L.RegFunction("set_parent", set_parent);
		L.RegFunction("get_invalidConNum", get_invalidConNum);
		L.RegFunction("set_invalidConNum", set_invalidConNum);
		L.RegFunction("get_Invalid", get_Invalid);
		L.RegFunction("set_Invalid", set_Invalid);
		L.RegFunction("get_Connections", get_Connections);
		L.RegFunction("get_Position", get_Position);
		L.RegFunction("set_Position", set_Position);
		L.RegFunction("DistanceTo", DistanceTo);
		L.RegFunction("get_gn", get_gn);
		L.RegFunction("set_gn", set_gn);
		L.RegFunction("get_fn", get_fn);
		L.RegFunction("sethn", sethn);
		L.RegFunction("getClientPos", getClientPos);
		L.RegFunction("getServerPos", getServerPos);
		L.RegFunction("New", _CreatePathNodeRealTime);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("connections", get_connections, set_connections);
		L.RegVar("_invalidConNum", get__invalidConNum, set__invalidConNum);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePathNodeRealTime(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				PathNodeRealTime obj = new PathNodeRealTime();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PathNodeRealTime.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_parent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			PathNodeRealTime o = obj.get_parent();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_parent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			PathNodeRealTime arg0 = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 2);
			obj.set_parent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_invalidConNum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			int o = obj.get_invalidConNum();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_invalidConNum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.set_invalidConNum(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Invalid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			bool o = obj.get_Invalid();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Invalid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.set_Invalid(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Connections(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			System.Collections.Generic.List<PathNodeRealTime> o = obj.get_Connections();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Position(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			UnityEngine.Vector2 o = obj.get_Position();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Position(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.set_Position(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DistanceTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			PathNodeRealTime arg0 = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 2);
			float o = obj.DistanceTo(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_gn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			float o = obj.get_gn();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_gn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.set_gn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			float o = obj.get_fn();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int sethn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			PathNodeRealTime arg0 = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 2);
			obj.sethn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getClientPos(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			UnityEngine.Vector3 o = obj.getClientPos();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getServerPos(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)ToLua.CheckObject<PathNodeRealTime>(L, 1);
			UnityEngine.Vector2 o = obj.getServerPos();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_connections(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)o;
			System.Collections.Generic.List<PathNodeRealTime> ret = obj.connections;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index connections on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__invalidConNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)o;
			int ret = obj._invalidConNum;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _invalidConNum on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_connections(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)o;
			System.Collections.Generic.List<PathNodeRealTime> arg0 = (System.Collections.Generic.List<PathNodeRealTime>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<PathNodeRealTime>));
			obj.connections = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index connections on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__invalidConNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PathNodeRealTime obj = (PathNodeRealTime)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj._invalidConNum = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _invalidConNum on a nil value");
		}
	}
}

