//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PlayerCamControlWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PlayerCamControl), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetCameraTarget", SetCameraTarget);
		L.RegFunction("SetCameraChangeMap", SetCameraChangeMap);
		L.RegFunction("GetMainCamera", GetMainCamera);
		L.RegFunction("SetShake", SetShake);
		L.RegFunction("SetFOV", SetFOV);
		L.RegFunction("ProcessFOV", ProcessFOV);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("CAMZ_DIS", get_CAMZ_DIS, set_CAMZ_DIS);
		L.RegVar("CAM_HEIGHT", get_CAM_HEIGHT, set_CAM_HEIGHT);
		L.RegVar("CAM_QUATERNION", get_CAM_QUATERNION, set_CAM_QUATERNION);
		L.RegVar("Instance", get_Instance, set_Instance);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCameraTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			UnityEngine.Component arg0 = (UnityEngine.Component)ToLua.CheckObject<UnityEngine.Component>(L, 2);
			obj.SetCameraTarget(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCameraChangeMap(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			obj.SetCameraChangeMap();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMainCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			UnityEngine.Camera o = obj.GetMainCamera();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
			obj.SetShake(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFOV(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
			obj.SetFOV(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessFOV(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PlayerCamControl obj = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.ProcessFOV(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CAMZ_DIS(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PlayerCamControl obj = (PlayerCamControl)o;
			float ret = obj.CAMZ_DIS;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CAMZ_DIS on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CAM_HEIGHT(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushnumber(L, PlayerCamControl.CAM_HEIGHT);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CAM_QUATERNION(IntPtr L)
	{
		try
		{
			ToLua.Push(L, PlayerCamControl.CAM_QUATERNION);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, PlayerCamControl.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CAMZ_DIS(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PlayerCamControl obj = (PlayerCamControl)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.CAMZ_DIS = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CAMZ_DIS on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CAM_HEIGHT(IntPtr L)
	{
		try
		{
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			PlayerCamControl.CAM_HEIGHT = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CAM_QUATERNION(IntPtr L)
	{
		try
		{
			UnityEngine.Quaternion arg0 = ToLua.ToQuaternion(L, 2);
			PlayerCamControl.CAM_QUATERNION = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Instance(IntPtr L)
	{
		try
		{
			PlayerCamControl arg0 = (PlayerCamControl)ToLua.CheckObject<PlayerCamControl>(L, 2);
			PlayerCamControl.Instance = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

