//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProxyWndFormWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProxyWndForm), typeof(System.Object));
		L.RegFunction("CreateWndForm", CreateWndForm);
		L.RegFunction("UpdateOrder", UpdateOrder);
		L.RegFunction("TopNode", TopNode);
		L.RegFunction("RemoveNode", RemoveNode);
		L.RegFunction("Update", Update);
		L.RegFunction("FreeWndForms", FreeWndForms);
		L.RegFunction("FadeOutWndForms", FadeOutWndForms);
		L.RegFunction("FadeOutWndForm", FadeOutWndForm);
		L.RegFunction("ProcessKeyClick", ProcessKeyClick);
		L.RegFunction("SetTop", SetTop);
		L.RegFunction("SetActive", SetActive);
		L.RegFunction("SetWndFormShift", SetWndFormShift);
		L.RegFunction("New", _CreateProxyWndForm);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("defaultDepth", get_defaultDepth, null);
		L.RegVar("rectTrans", get_rectTrans, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProxyWndForm(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProxyWndForm obj = new ProxyWndForm();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				ProxyWndForm obj = new ProxyWndForm(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
				ProxyWndForm obj = new ProxyWndForm(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProxyWndForm.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateWndForm(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				WndForm o = obj.CreateWndForm(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				WndForm o = obj.CreateWndForm(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ProxyWndForm.CreateWndForm");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateOrder(ref arg0);
			LuaDLL.lua_pushinteger(L, arg0);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TopNode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			WndFormNode arg0 = (WndFormNode)ToLua.CheckObject<WndFormNode>(L, 2);
			obj.TopNode(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveNode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			WndFormNode arg0 = (WndFormNode)ToLua.CheckObject<WndFormNode>(L, 2);
			obj.RemoveNode(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FreeWndForms(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				obj.FreeWndForms();
				return 0;
			}
			else if (count == 2)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
				obj.FreeWndForms(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ProxyWndForm.FreeWndForms");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeOutWndForms(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				obj.FadeOutWndForms(arg0);
				return 0;
			}
			else if (count == 3)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
				uint arg1 = (uint)LuaDLL.luaL_checknumber(L, 3);
				obj.FadeOutWndForms(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ProxyWndForm.FadeOutWndForms");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeOutWndForm(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			uint arg1 = (uint)LuaDLL.luaL_checknumber(L, 3);
			obj.FadeOutWndForm(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessKeyClick(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				bool o = obj.ProcessKeyClick(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				UnityEngine.EventType arg1 = (UnityEngine.EventType)ToLua.CheckObject(L, 3, typeof(UnityEngine.EventType));
				bool o = obj.ProcessKeyClick(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 4)
			{
				ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				UnityEngine.EventType arg1 = (UnityEngine.EventType)ToLua.CheckObject(L, 3, typeof(UnityEngine.EventType));
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				bool o = obj.ProcessKeyClick(arg0, arg1, arg2);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ProxyWndForm.ProcessKeyClick");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			obj.SetTop();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetActive(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetActive(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetWndFormShift(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyWndForm obj = (ProxyWndForm)ToLua.CheckObject<ProxyWndForm>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetWndFormShift(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_defaultDepth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProxyWndForm obj = (ProxyWndForm)o;
			int ret = obj.defaultDepth;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index defaultDepth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rectTrans(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProxyWndForm obj = (ProxyWndForm)o;
			UnityEngine.RectTransform ret = obj.rectTrans;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rectTrans on a nil value");
		}
	}
}

