//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ResMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ResMgr), typeof(System.Object));
		L.RegFunction("IsUIFXReady", IsUIFXReady);
		L.RegFunction("LoadBaseUIText", LoadBaseUIText);
		L.RegFunction("LoadBaseUITextAgain", LoadBaseUITextAgain);
		L.RegFunction("GetBasicUIText", GetBasicUIText);
		L.RegFunction("GetUIParticle", GetUIParticle);
		L.RegFunction("GetSGCInitSettings", GetSGCInitSettings);
		L.RegFunction("GetLuaBundleName", GetLuaBundleName);
		L.RegFunction("IsSceneReady", IsSceneReady);
		L.RegFunction("LoadScene", LoadScene);
		L.RegFunction("UnloadScene", UnloadScene);
		L.RegFunction("New", _CreateResMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("sVersionTag", get_sVersionTag, set_sVersionTag);
		L.RegVar("serverListData", get_serverListData, set_serverListData);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateResMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ResMgr obj = new ResMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ResMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsUIFXReady(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsUIFXReady(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadBaseUIText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			obj.LoadBaseUIText();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadBaseUITextAgain(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			obj.LoadBaseUITextAgain();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBasicUIText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string o = obj.GetBasicUIText(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUIParticle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.GetUIParticle(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSGCInitSettings(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string o = obj.GetSGCInitSettings(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaBundleName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string o = obj.GetLuaBundleName();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsSceneReady(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsSceneReady(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			float o = obj.LoadScene(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ResMgr obj = (ResMgr)ToLua.CheckObject<ResMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.UnloadScene(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sVersionTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ResMgr obj = (ResMgr)o;
			string ret = obj.sVersionTag;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sVersionTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_serverListData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ResMgr obj = (ResMgr)o;
			System.Collections.Generic.List<ServerListData> ret = obj.serverListData;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index serverListData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, ResMgr.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sVersionTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ResMgr obj = (ResMgr)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.sVersionTag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sVersionTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_serverListData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ResMgr obj = (ResMgr)o;
			System.Collections.Generic.List<ServerListData> arg0 = (System.Collections.Generic.List<ServerListData>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<ServerListData>));
			obj.serverListData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index serverListData on a nil value");
		}
	}
}

