//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SoundProxyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SoundProxy), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("get_main", get_main);
		L.RegFunction("get_Disable", get_Disable);
		L.RegFunction("set_Disable", set_Disable);
		L.RegFunction("get_masterVolume", get_masterVolume);
		L.RegFunction("set_masterVolume", set_masterVolume);
		L.RegFunction("get_dubbingVolume", get_dubbingVolume);
		L.RegFunction("set_dubbingVolume", set_dubbingVolume);
		L.RegFunction("Save", Save);
		L.RegFunction("get_audio3D", get_audio3D);
		L.RegFunction("get_isPlaying", get_isPlaying);
		L.RegFunction("AudioSourcePlay", AudioSourcePlay);
		L.RegFunction("AudioSourceStop", AudioSourceStop);
		L.RegFunction("Play", Play);
		L.RegFunction("PlaySoundForLoop", PlaySoundForLoop);
		L.RegFunction("StopSoundForLoop", StopSoundForLoop);
		L.RegFunction("PlaySoundByName", PlaySoundByName);
		L.RegFunction("Play3DSoundByName", Play3DSoundByName);
		L.RegFunction("Play3D", Play3D);
		L.RegFunction("PlaySound", PlaySound);
		L.RegFunction("PlayDubbingSoundByName", PlayDubbingSoundByName);
		L.RegFunction("StopDubbingSound", StopDubbingSound);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("CMinVolume", 0);
		L.RegConstant("CMaxVoulume", 1);
		L.RegVar("_isMain", get__isMain, set__isMain);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_main(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SoundProxy o = SoundProxy.get_main();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Disable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = SoundProxy.get_Disable();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Disable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			SoundProxy.set_Disable(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_masterVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			float o = SoundProxy.get_masterVolume();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_masterVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			SoundProxy.set_masterVolume(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dubbingVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			float o = SoundProxy.get_dubbingVolume();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dubbingVolume(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			SoundProxy.set_dubbingVolume(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Save(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			SoundProxy.Save(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_audio3D(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			UnityEngine.AudioSource o = obj.get_audio3D();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isPlaying(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			bool o = obj.get_isPlaying();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AudioSourcePlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
			obj.AudioSourcePlay(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AudioSourceStop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			obj.AudioSourceStop();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				bool o = obj.Play(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool o = obj.Play(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				bool o = obj.Play(arg0, arg1, arg2);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.Play");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaySoundForLoop(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				obj.PlaySoundForLoop(arg0);
				return 0;
			}
			else if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.PlaySoundForLoop(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				obj.PlaySoundForLoop(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
				obj.PlaySoundForLoop(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.PlaySoundForLoop");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopSoundForLoop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			string arg0 = ToLua.CheckString(L, 2);
			obj.StopSoundForLoop(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaySoundByName(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				obj.PlaySoundByName(arg0);
				return 0;
			}
			else if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.PlaySoundByName(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				obj.PlaySoundByName(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
				obj.PlaySoundByName(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.PlaySoundByName");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play3DSoundByName(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				obj.Play3DSoundByName(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				obj.Play3DSoundByName(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
				obj.Play3DSoundByName(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (count == 6)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg4 = LuaDLL.luaL_checkboolean(L, 6);
				obj.Play3DSoundByName(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.Play3DSoundByName");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play3D(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				obj.Play3D(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				obj.Play3D(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				UnityEngine.AudioClip arg0 = (UnityEngine.AudioClip)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioClip));
				UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
				obj.Play3D(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.Play3D");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaySound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			UnityEngine.AudioSource arg0 = (UnityEngine.AudioSource)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioSource));
			obj.PlaySound(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayDubbingSoundByName(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				obj.PlayDubbingSoundByName(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.PlayDubbingSoundByName(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
				obj.PlayDubbingSoundByName(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (count == 6)
			{
				SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
				string arg0 = ToLua.CheckString(L, 2);
				float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 5);
				bool arg4 = LuaDLL.luaL_checkboolean(L, 6);
				obj.PlayDubbingSoundByName(arg0, arg1, arg2, arg3, arg4);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SoundProxy.PlayDubbingSoundByName");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopDubbingSound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SoundProxy obj = (SoundProxy)ToLua.CheckObject(L, 1, typeof(SoundProxy));
			obj.StopDubbingSound();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__isMain(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SoundProxy obj = (SoundProxy)o;
			bool ret = obj._isMain;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _isMain on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__isMain(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SoundProxy obj = (SoundProxy)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj._isMain = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _isMain on a nil value");
		}
	}
}

