//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SpriteManagerPoolWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SpriteManagerPool), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("moveSpriteMgrToCenter", moveSpriteMgrToCenter);
		L.RegFunction("IsSpriteReady", IsSpriteReady);
		L.RegFunction("createSprite", createSprite);
		L.RegFunction("createSpriteUI", createSpriteUI);
		L.RegFunction("removeSprite", removeSprite);
		L.RegFunction("getShadow", getShadow);
		L.RegFunction("IsShadowReady", IsShadowReady);
		L.RegFunction("createShadow", createShadow);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int moveSpriteMgrToCenter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			obj.moveSpriteMgrToCenter();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsSpriteReady(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsSpriteReady(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int createSprite(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				PackedSprite o = obj.createSprite(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 3)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				PackedSprite o = obj.createSprite(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 4)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 5)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 6)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 7)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 8)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 9)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 10)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 11)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 12)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 13)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 14)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 15)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 16)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 17)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				byte arg15 = (byte)LuaDLL.luaL_checknumber(L, 17);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 18)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				byte arg15 = (byte)LuaDLL.luaL_checknumber(L, 17);
				byte arg16 = (byte)LuaDLL.luaL_checknumber(L, 18);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 19)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				byte arg15 = (byte)LuaDLL.luaL_checknumber(L, 17);
				byte arg16 = (byte)LuaDLL.luaL_checknumber(L, 18);
				byte arg17 = (byte)LuaDLL.luaL_checknumber(L, 19);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 20)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				byte arg15 = (byte)LuaDLL.luaL_checknumber(L, 17);
				byte arg16 = (byte)LuaDLL.luaL_checknumber(L, 18);
				byte arg17 = (byte)LuaDLL.luaL_checknumber(L, 19);
				byte arg18 = (byte)LuaDLL.luaL_checknumber(L, 20);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 21)
			{
				SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				byte arg1 = (byte)LuaDLL.luaL_checknumber(L, 3);
				byte arg2 = (byte)LuaDLL.luaL_checknumber(L, 4);
				byte arg3 = (byte)LuaDLL.luaL_checknumber(L, 5);
				byte arg4 = (byte)LuaDLL.luaL_checknumber(L, 6);
				byte arg5 = (byte)LuaDLL.luaL_checknumber(L, 7);
				byte arg6 = (byte)LuaDLL.luaL_checknumber(L, 8);
				byte arg7 = (byte)LuaDLL.luaL_checknumber(L, 9);
				byte arg8 = (byte)LuaDLL.luaL_checknumber(L, 10);
				bool arg9 = LuaDLL.luaL_checkboolean(L, 11);
				bool arg10 = LuaDLL.luaL_checkboolean(L, 12);
				byte arg11 = (byte)LuaDLL.luaL_checknumber(L, 13);
				bool arg12 = LuaDLL.luaL_checkboolean(L, 14);
				byte arg13 = (byte)LuaDLL.luaL_checknumber(L, 15);
				byte arg14 = (byte)LuaDLL.luaL_checknumber(L, 16);
				byte arg15 = (byte)LuaDLL.luaL_checknumber(L, 17);
				byte arg16 = (byte)LuaDLL.luaL_checknumber(L, 18);
				byte arg17 = (byte)LuaDLL.luaL_checknumber(L, 19);
				byte arg18 = (byte)LuaDLL.luaL_checknumber(L, 20);
				byte arg19 = (byte)LuaDLL.luaL_checknumber(L, 21);
				PackedSprite o = obj.createSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SpriteManagerPool.createSprite");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int createSpriteUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			SpriteManager arg1 = (SpriteManager)ToLua.CheckObject<SpriteManager>(L, 3);
			PackedSprite o = obj.createSpriteUI(arg0, ref arg1);
			ToLua.Push(L, o);
			ToLua.Push(L, arg1);
			return 2;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int removeSprite(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			SpriteRoot arg0 = (SpriteRoot)ToLua.CheckObject<SpriteRoot>(L, 2);
			obj.removeSprite(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getShadow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			PackedSprite o = obj.getShadow();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsShadowReady(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsShadowReady(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int createShadow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteManagerPool obj = (SpriteManagerPool)ToLua.CheckObject<SpriteManagerPool>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			PackedSprite o = obj.createShadow(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, SpriteManagerPool.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

