//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SpriteBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SpriteBase), typeof(SpriteRoot));
		L.RegFunction("Start", Start);
		L.RegFunction("Clear", Clear);
		L.RegFunction("Delete", Delete);
		L.RegFunction("Copy", Copy);
		L.RegFunction("Hide", Hide);
		L.RegFunction("SetAnimCompleteDelegate", SetAnimCompleteDelegate);
		L.RegFunction("SetAnimFrameDelegate", SetAnimFrameDelegate);
		L.RegFunction("SetSpriteResizedDelegate", SetSpriteResizedDelegate);
		L.RegFunction("AddSpriteResizedDelegate", AddSpriteResizedDelegate);
		L.RegFunction("RemoveSpriteresizedDelegate", RemoveSpriteresizedDelegate);
		L.RegFunction("StepAnim", StepAnim);
		L.RegFunction("PlayAnim", PlayAnim);
		L.RegFunction("PlayAnimInReverse", PlayAnimInReverse);
		L.RegFunction("SetFramerate", SetFramerate);
		L.RegFunction("PauseAnim", PauseAnim);
		L.RegFunction("StopAnim", StopAnim);
		L.RegFunction("RevertToStatic", RevertToStatic);
		L.RegFunction("IsAnimating", IsAnimating);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("playAnimOnStart", get_playAnimOnStart, set_playAnimOnStart);
		L.RegVar("crossfadeFrames", get_crossfadeFrames, set_crossfadeFrames);
		L.RegVar("defaultAnim", get_defaultAnim, set_defaultAnim);
		L.RegVar("Animating", get_Animating, set_Animating);
		L.RegVar("CurAnimIndex", get_CurAnimIndex, set_CurAnimIndex);
		L.RegFunction("AnimCompleteDelegate", SpriteBase_AnimCompleteDelegate);
		L.RegFunction("AnimFrameDelegate", SpriteBase_AnimFrameDelegate);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.Start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Delete(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.Delete();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Copy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteRoot arg0 = (SpriteRoot)ToLua.CheckObject<SpriteRoot>(L, 2);
			obj.Copy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Hide(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.Hide(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAnimCompleteDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteBase.AnimCompleteDelegate arg0 = (SpriteBase.AnimCompleteDelegate)ToLua.CheckDelegate<SpriteBase.AnimCompleteDelegate>(L, 2);
			obj.SetAnimCompleteDelegate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAnimFrameDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteBase.AnimFrameDelegate arg0 = (SpriteBase.AnimFrameDelegate)ToLua.CheckDelegate<SpriteBase.AnimFrameDelegate>(L, 2);
			obj.SetAnimFrameDelegate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSpriteResizedDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteRoot.SpriteResizedDelegate arg0 = (SpriteRoot.SpriteResizedDelegate)ToLua.CheckDelegate<SpriteRoot.SpriteResizedDelegate>(L, 2);
			obj.SetSpriteResizedDelegate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddSpriteResizedDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteRoot.SpriteResizedDelegate arg0 = (SpriteRoot.SpriteResizedDelegate)ToLua.CheckDelegate<SpriteRoot.SpriteResizedDelegate>(L, 2);
			obj.AddSpriteResizedDelegate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveSpriteresizedDelegate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			SpriteRoot.SpriteResizedDelegate arg0 = (SpriteRoot.SpriteResizedDelegate)ToLua.CheckDelegate<SpriteRoot.SpriteResizedDelegate>(L, 2);
			obj.RemoveSpriteresizedDelegate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StepAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.StepAnim(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAnim(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.PlayAnim(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.PlayAnim(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SpriteBase.PlayAnim");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayAnimInReverse(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.PlayAnimInReverse(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.PlayAnimInReverse(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: SpriteBase.PlayAnimInReverse");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFramerate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetFramerate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PauseAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.PauseAnim();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.StopAnim();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RevertToStatic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			obj.RevertToStatic();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAnimating(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SpriteBase obj = (SpriteBase)ToLua.CheckObject<SpriteBase>(L, 1);
			bool o = obj.IsAnimating();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_playAnimOnStart(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool ret = obj.playAnimOnStart;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index playAnimOnStart on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_crossfadeFrames(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool ret = obj.crossfadeFrames;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index crossfadeFrames on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_defaultAnim(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			int ret = obj.defaultAnim;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index defaultAnim on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Animating(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool ret = obj.Animating;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Animating on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurAnimIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			int ret = obj.CurAnimIndex;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurAnimIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_playAnimOnStart(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.playAnimOnStart = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index playAnimOnStart on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_crossfadeFrames(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.crossfadeFrames = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index crossfadeFrames on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_defaultAnim(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.defaultAnim = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index defaultAnim on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Animating(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.Animating = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Animating on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurAnimIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteBase obj = (SpriteBase)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.CurAnimIndex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurAnimIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SpriteBase_AnimCompleteDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<SpriteBase.AnimCompleteDelegate>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<SpriteBase.AnimCompleteDelegate>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SpriteBase_AnimFrameDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<SpriteBase.AnimFrameDelegate>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<SpriteBase.AnimFrameDelegate>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

