//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class tageventDATAWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(tageventDATA), typeof(System.Object));
		L.RegFunction("ByteArrayToStructure", ByteArrayToStructure);
		L.RegFunction("StructureToByteArray", StructureToByteArray);
		L.RegFunction("New", _CreatetageventDATA);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("eveHardLevel", get_eveHardLevel, set_eveHardLevel);
		L.RegVar("eveCode", get_eveCode, set_eveCode);
		L.RegVar("eveX", get_eveX, set_eveX);
		L.RegVar("eveY", get_eveY, set_eveY);
		L.RegVar("eveItem", get_eveItem, set_eveItem);
		L.RegVar("eveData", get_eveData, set_eveData);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatetageventDATA(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				tageventDATA obj = new tageventDATA();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: tageventDATA.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ByteArrayToStructure(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				tageventDATA obj = (tageventDATA)ToLua.CheckObject<tageventDATA>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				int o = obj.ByteArrayToStructure(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3)
			{
				tageventDATA obj = (tageventDATA)ToLua.CheckObject<tageventDATA>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int o = obj.ByteArrayToStructure(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: tageventDATA.ByteArrayToStructure");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StructureToByteArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			tageventDATA obj = (tageventDATA)ToLua.CheckObject<tageventDATA>(L, 1);
			byte[] o = obj.StructureToByteArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveHardLevel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int ret = obj.eveHardLevel;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveHardLevel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveCode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int ret = obj.eveCode;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveCode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveX(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int ret = obj.eveX;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveX on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int ret = obj.eveY;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveItem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int[] ret = obj.eveItem;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveItem on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eveData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int[] ret = obj.eveData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveHardLevel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.eveHardLevel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveHardLevel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveCode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.eveCode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveCode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveX(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.eveX = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveX on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveY(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.eveY = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveY on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveItem(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int[] arg0 = ToLua.CheckNumberArray<int>(L, 2);
			obj.eveItem = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveItem on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eveData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tageventDATA obj = (tageventDATA)o;
			int[] arg0 = ToLua.CheckNumberArray<int>(L, 2);
			obj.eveData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eveData on a nil value");
		}
	}
}

