//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class tagmapCODEDATAWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(tagmapCODEDATA), typeof(System.Object));
		L.RegFunction("ByteArrayToStructure", ByteArrayToStructure);
		L.RegFunction("StructureToByteArray", StructureToByteArray);
		L.RegFunction("New", _CreatetagmapCODEDATA);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("mapCode", get_mapCode, set_mapCode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatetagmapCODEDATA(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				tagmapCODEDATA obj = new tagmapCODEDATA();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: tagmapCODEDATA.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ByteArrayToStructure(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				tagmapCODEDATA obj = (tagmapCODEDATA)ToLua.CheckObject<tagmapCODEDATA>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				int o = obj.ByteArrayToStructure(arg0);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 3)
			{
				tagmapCODEDATA obj = (tagmapCODEDATA)ToLua.CheckObject<tagmapCODEDATA>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int o = obj.ByteArrayToStructure(arg0, arg1);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: tagmapCODEDATA.ByteArrayToStructure");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StructureToByteArray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			tagmapCODEDATA obj = (tagmapCODEDATA)ToLua.CheckObject<tagmapCODEDATA>(L, 1);
			byte[] o = obj.StructureToByteArray();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mapCode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tagmapCODEDATA obj = (tagmapCODEDATA)o;
			uint ret = obj.mapCode;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mapCode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mapCode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			tagmapCODEDATA obj = (tagmapCODEDATA)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.mapCode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mapCode on a nil value");
		}
	}
}

