//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TResource_UnityEngine_GameObjectWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TResource<UnityEngine.GameObject>), typeof(ResourceBase), "TResource_UnityEngine_GameObject");
		L.RegFunction("Load", Load);
		L.RegFunction("Unload", Unload);
		L.RegFunction("New", _CreateTResource_UnityEngine_GameObject);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("callback", get_callback, set_callback);
		L.RegVar("data", get_data, set_data);
		L.RegVar("assetType", get_assetType, set_assetType);
		L.RegFunction("cbFunction", TResource_UnityEngine_GameObject_cbFunction);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTResource_UnityEngine_GameObject(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TResource<UnityEngine.GameObject> obj = new TResource<UnityEngine.GameObject>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TResource<UnityEngine.GameObject>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)ToLua.CheckObject<TResource<UnityEngine.GameObject>>(L, 1);
			bool o = obj.Load();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Unload(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)ToLua.CheckObject<TResource<UnityEngine.GameObject>>(L, 1);
			obj.Unload();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_callback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			TResource<UnityEngine.GameObject>.cbFunction ret = obj.callback;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index callback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			UnityEngine.GameObject ret = obj.data;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_assetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			ResourcesLoader.AssetType ret = obj.assetType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index assetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_callback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			TResource<UnityEngine.GameObject>.cbFunction arg0 = (TResource<UnityEngine.GameObject>.cbFunction)ToLua.CheckDelegate<TResource<UnityEngine.GameObject>.cbFunction>(L, 2);
			obj.callback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index callback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_assetType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			TResource<UnityEngine.GameObject> obj = (TResource<UnityEngine.GameObject>)o;
			ResourcesLoader.AssetType arg0 = (ResourcesLoader.AssetType)ToLua.CheckObject(L, 2, typeof(ResourcesLoader.AssetType));
			obj.assetType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index assetType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TResource_UnityEngine_GameObject_cbFunction(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<TResource<UnityEngine.GameObject>.cbFunction>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<TResource<UnityEngine.GameObject>.cbFunction>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

