//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UICurrencyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UICurrency), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetCurrency", SetCurrency);
		L.RegFunction("SetCurrencyOnly", SetCurrencyOnly);
		L.RegFunction("SetCurrencyWithColor", SetCurrencyWithColor);
		L.RegFunction("SetCurrencyString", SetCurrencyString);
		L.RegFunction("SetCurrencyStringOnly", SetCurrencyStringOnly);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("CurrencyIcon", get_CurrencyIcon, set_CurrencyIcon);
		L.RegVar("_Count", get__Count, set__Count);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrency(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.SetCurrency(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				obj.SetCurrency(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UICurrency.SetCurrency");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrencyOnly(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetCurrencyOnly(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrencyWithColor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.SetCurrencyWithColor(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrencyString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.SetCurrencyString(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrencyStringOnly(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UICurrency obj = (UICurrency)ToLua.CheckObject<UICurrency>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetCurrencyStringOnly(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrencyIcon(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UICurrency obj = (UICurrency)o;
			UIImagePicker ret = obj.CurrencyIcon;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrencyIcon on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__Count(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UICurrency obj = (UICurrency)o;
			UnityEngine.UI.Text ret = obj._Count;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _Count on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurrencyIcon(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UICurrency obj = (UICurrency)o;
			UIImagePicker arg0 = (UIImagePicker)ToLua.CheckObject<UIImagePicker>(L, 2);
			obj.CurrencyIcon = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurrencyIcon on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__Count(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UICurrency obj = (UICurrency)o;
			UnityEngine.UI.Text arg0 = (UnityEngine.UI.Text)ToLua.CheckObject<UnityEngine.UI.Text>(L, 2);
			obj._Count = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _Count on a nil value");
		}
	}
}

