//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIImagePickerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIImagePicker), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetCurTag", GetCurTag);
		L.RegFunction("SetCurTag", SetCurTag);
		L.RegFunction("SetCurTagByIndex", SetCurTagByIndex);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("CurTag", get_CurTag, set_CurTag);
		L.RegVar("uiImagePickerAsset", get_uiImagePickerAsset, set_uiImagePickerAsset);
		L.RegVar("bSetNative", get_bSetNative, set_bSetNative);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurTag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIImagePicker obj = (UIImagePicker)ToLua.CheckObject<UIImagePicker>(L, 1);
			string o = obj.GetCurTag();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurTag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIImagePicker obj = (UIImagePicker)ToLua.CheckObject<UIImagePicker>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetCurTag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurTagByIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIImagePicker obj = (UIImagePicker)ToLua.CheckObject<UIImagePicker>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetCurTagByIndex(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			string ret = obj.CurTag;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiImagePickerAsset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			UIImagePickerAsset ret = obj.uiImagePickerAsset;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiImagePickerAsset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bSetNative(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			bool ret = obj.bSetNative;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bSetNative on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.CurTag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiImagePickerAsset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			UIImagePickerAsset arg0 = (UIImagePickerAsset)ToLua.CheckObject<UIImagePickerAsset>(L, 2);
			obj.uiImagePickerAsset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiImagePickerAsset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bSetNative(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImagePicker obj = (UIImagePicker)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.bSetNative = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index bSetNative on a nil value");
		}
	}
}

