//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIImageColorPickerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIImageColorPicker), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetCurTag", GetCurTag);
		L.RegFunction("SetCurTag", SetCurTag);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("CurTag", get_CurTag, set_CurTag);
		L.RegVar("uiColorPickerAsset", get_uiColorPickerAsset, set_uiColorPickerAsset);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurTag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UIImageColorPicker obj = (UIImageColorPicker)ToLua.CheckObject<UIImageColorPicker>(L, 1);
			string o = obj.GetCurTag();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurTag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIImageColorPicker obj = (UIImageColorPicker)ToLua.CheckObject<UIImageColorPicker>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetCurTag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImageColorPicker obj = (UIImageColorPicker)o;
			string ret = obj.CurTag;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_uiColorPickerAsset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImageColorPicker obj = (UIImageColorPicker)o;
			UIImageColorPickerAsset ret = obj.uiColorPickerAsset;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiColorPickerAsset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CurTag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImageColorPicker obj = (UIImageColorPicker)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.CurTag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CurTag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_uiColorPickerAsset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UIImageColorPicker obj = (UIImageColorPicker)o;
			UIImageColorPickerAsset arg0 = (UIImageColorPickerAsset)ToLua.CheckObject<UIImageColorPickerAsset>(L, 2);
			obj.uiColorPickerAsset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index uiColorPickerAsset on a nil value");
		}
	}
}

