//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UISizeControlWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UISizeControl), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetMaxWidth", SetMaxWidth);
		L.RegFunction("SetMaxHeight", SetMaxHeight);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("_maxWidth", get__maxWidth, set__maxWidth);
		L.RegVar("_maxHeight", get__maxHeight, set__maxHeight);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMaxWidth(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UISizeControl obj = (UISizeControl)ToLua.CheckObject<UISizeControl>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetMaxWidth(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMaxHeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UISizeControl obj = (UISizeControl)ToLua.CheckObject<UISizeControl>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetMaxHeight(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__maxWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UISizeControl obj = (UISizeControl)o;
			float ret = obj._maxWidth;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _maxWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__maxHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UISizeControl obj = (UISizeControl)o;
			float ret = obj._maxHeight;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _maxHeight on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__maxWidth(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UISizeControl obj = (UISizeControl)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj._maxWidth = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _maxWidth on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__maxHeight(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UISizeControl obj = (UISizeControl)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj._maxHeight = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _maxHeight on a nil value");
		}
	}
}

