//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UITweenerGroupWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UITweenerGroup), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Reset", Reset);
		L.RegFunction("ResetToBeginning", ResetToBeginning);
		L.RegFunction("PlayForward", PlayForward);
		L.RegFunction("PlayReverse", PlayReverse);
		L.RegFunction("SetOnFinished", SetOnFinished);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("lastTween", get_lastTween, set_lastTween);
		L.RegVar("tweenCount", get_tweenCount, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UITweenerGroup obj = (UITweenerGroup)ToLua.CheckObject<UITweenerGroup>(L, 1);
			obj.Reset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetToBeginning(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UITweenerGroup obj = (UITweenerGroup)ToLua.CheckObject<UITweenerGroup>(L, 1);
			obj.ResetToBeginning();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayForward(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UITweenerGroup obj = (UITweenerGroup)ToLua.CheckObject<UITweenerGroup>(L, 1);
			obj.PlayForward();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayReverse(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UITweenerGroup obj = (UITweenerGroup)ToLua.CheckObject<UITweenerGroup>(L, 1);
			obj.PlayReverse();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetOnFinished(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UITweenerGroup obj = (UITweenerGroup)ToLua.CheckObject<UITweenerGroup>(L, 1);
			EventDelegate.Callback arg0 = (EventDelegate.Callback)ToLua.CheckDelegate<EventDelegate.Callback>(L, 2);
			obj.SetOnFinished(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_lastTween(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UITweenerGroup obj = (UITweenerGroup)o;
			UITweener ret = obj.lastTween;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index lastTween on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tweenCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UITweenerGroup obj = (UITweenerGroup)o;
			int ret = obj.tweenCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tweenCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_lastTween(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UITweenerGroup obj = (UITweenerGroup)o;
			UITweener arg0 = (UITweener)ToLua.CheckObject<UITweener>(L, 2);
			obj.lastTween = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index lastTween on a nil value");
		}
	}
}

