//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ImageConversionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ImageConversion");
		L.RegFunction("EncodeToTGA", EncodeToTGA);
		L.RegFunction("EncodeToPNG", EncodeToPNG);
		L.RegFunction("EncodeToJPG", EncodeToJPG);
		L.RegFunction("EncodeToEXR", EncodeToEXR);
		L.RegFunction("LoadImage", LoadImage);
		L.RegFunction("EncodeArrayToTGA", EncodeArrayToTGA);
		L.RegFunction("EncodeArrayToPNG", EncodeArrayToPNG);
		L.RegFunction("EncodeArrayToJPG", EncodeArrayToJPG);
		L.RegFunction("EncodeArrayToEXR", EncodeArrayToEXR);
		L.RegVar("EnableLegacyPngGammaRuntimeLoadBehavior", get_EnableLegacyPngGammaRuntimeLoadBehavior, set_EnableLegacyPngGammaRuntimeLoadBehavior);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeToTGA(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
			byte[] o = UnityEngine.ImageConversion.EncodeToTGA(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeToPNG(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
			byte[] o = UnityEngine.ImageConversion.EncodeToPNG(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeToJPG(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				byte[] o = UnityEngine.ImageConversion.EncodeToJPG(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
				byte[] o = UnityEngine.ImageConversion.EncodeToJPG(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeToJPG");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeToEXR(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				byte[] o = UnityEngine.ImageConversion.EncodeToEXR(arg0);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				UnityEngine.Texture2D.EXRFlags arg1 = (UnityEngine.Texture2D.EXRFlags)ToLua.CheckObject(L, 2, typeof(UnityEngine.Texture2D.EXRFlags));
				byte[] o = UnityEngine.ImageConversion.EncodeToEXR(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeToEXR");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadImage(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				byte[] arg1 = ToLua.CheckByteBuffer(L, 2);
				bool o = UnityEngine.ImageConversion.LoadImage(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				UnityEngine.Texture2D arg0 = (UnityEngine.Texture2D)ToLua.CheckObject(L, 1, typeof(UnityEngine.Texture2D));
				byte[] arg1 = ToLua.CheckByteBuffer(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				bool o = UnityEngine.ImageConversion.LoadImage(arg0, arg1, arg2);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.LoadImage");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeArrayToTGA(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToTGA(arg0, arg1, arg2, arg3);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 5)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToTGA(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeArrayToTGA");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeArrayToPNG(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToPNG(arg0, arg1, arg2, arg3);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 5)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToPNG(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeArrayToPNG");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeArrayToJPG(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToJPG(arg0, arg1, arg2, arg3);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 5)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToJPG(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 6)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				int arg5 = (int)LuaDLL.luaL_checknumber(L, 6);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToJPG(arg0, arg1, arg2, arg3, arg4, arg5);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeArrayToJPG");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EncodeArrayToEXR(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToEXR(arg0, arg1, arg2, arg3);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 5)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToEXR(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 6)
			{
				System.Array arg0 = (System.Array)ToLua.CheckObject<System.Array>(L, 1);
				UnityEngine.Experimental.Rendering.GraphicsFormat arg1 = (UnityEngine.Experimental.Rendering.GraphicsFormat)ToLua.CheckObject(L, 2, typeof(UnityEngine.Experimental.Rendering.GraphicsFormat));
				uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 3);
				uint arg3 = (uint)LuaDLL.luaL_checknumber(L, 4);
				uint arg4 = (uint)LuaDLL.luaL_checknumber(L, 5);
				UnityEngine.Texture2D.EXRFlags arg5 = (UnityEngine.Texture2D.EXRFlags)ToLua.CheckObject(L, 6, typeof(UnityEngine.Texture2D.EXRFlags));
				byte[] o = UnityEngine.ImageConversion.EncodeArrayToEXR(arg0, arg1, arg2, arg3, arg4, arg5);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.ImageConversion.EncodeArrayToEXR");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EnableLegacyPngGammaRuntimeLoadBehavior(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, UnityEngine.ImageConversion.EnableLegacyPngGammaRuntimeLoadBehavior);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_EnableLegacyPngGammaRuntimeLoadBehavior(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			UnityEngine.ImageConversion.EnableLegacyPngGammaRuntimeLoadBehavior = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

