//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UVAnimationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UVAnimation), typeof(System.Object));
		L.RegFunction("Clone", Clone);
		L.RegFunction("Reset", Reset);
		L.RegFunction("PlayInReverse", PlayInReverse);
		L.RegFunction("SetStepDir", SetStepDir);
		L.RegFunction("GetNextFrame", GetNextFrame);
		L.RegFunction("GetCurrentFrame", GetCurrentFrame);
		L.RegFunction("GetFrame", GetFrame);
		L.RegFunction("BuildUVAnim", BuildUVAnim);
		L.RegFunction("BuildWrappedUVAnim", BuildWrappedUVAnim);
		L.RegFunction("SetAnim", SetAnim);
		L.RegFunction("AppendAnim", AppendAnim);
		L.RegFunction("SetCurrentFrame", SetCurrentFrame);
		L.RegFunction("SetPosition", SetPosition);
		L.RegFunction("SetClipPosition", SetClipPosition);
		L.RegFunction("GetLength", GetLength);
		L.RegFunction("GetDuration", GetDuration);
		L.RegFunction("GetFrameCount", GetFrameCount);
		L.RegFunction("GetFramesDisplayed", GetFramesDisplayed);
		L.RegFunction("GetCurPosition", GetCurPosition);
		L.RegFunction("New", _CreateUVAnimation);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("name", get_name, set_name);
		L.RegVar("loopCycles", get_loopCycles, set_loopCycles);
		L.RegVar("loopReverse", get_loopReverse, set_loopReverse);
		L.RegVar("framerate", get_framerate, set_framerate);
		L.RegVar("index", get_index, set_index);
		L.RegVar("onAnimEnd", get_onAnimEnd, set_onAnimEnd);
		L.RegVar("StepDirection", get_StepDirection, set_StepDirection);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUVAnimation(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UVAnimation obj = new UVAnimation();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				UVAnimation arg0 = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
				UVAnimation obj = new UVAnimation(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UVAnimation.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clone(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			UVAnimation o = obj.Clone();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			obj.Reset();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayInReverse(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			obj.PlayInReverse();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetStepDir(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetStepDir(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNextFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			SPRITE_FRAME arg0 = StackTraits<SPRITE_FRAME>.Check(L, 2);
			bool o = obj.GetNextFrame(ref arg0);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.PushValue(L, arg0);
			return 2;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurrentFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			SPRITE_FRAME o = obj.GetCurrentFrame();
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			SPRITE_FRAME o = obj.GetFrame(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BuildUVAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			int arg4 = (int)LuaDLL.luaL_checknumber(L, 6);
			SPRITE_FRAME[] o = obj.BuildUVAnim(arg0, arg1, arg2, arg3, arg4);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BuildWrappedUVAnim(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				SPRITE_FRAME[] o = obj.BuildWrappedUVAnim(arg0, arg1, arg2);
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 6)
			{
				UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
				int arg4 = (int)LuaDLL.luaL_checknumber(L, 6);
				SPRITE_FRAME[] o = obj.BuildWrappedUVAnim(arg0, arg1, arg2, arg3, arg4);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UVAnimation.BuildWrappedUVAnim");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAnim(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
				SPRITE_FRAME[] arg0 = ToLua.CheckStructArray<SPRITE_FRAME>(L, 2);
				obj.SetAnim(arg0);
				return 0;
			}
			else if (count == 3)
			{
				UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
				TextureAnim arg0 = (TextureAnim)ToLua.CheckObject<TextureAnim>(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.SetAnim(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UVAnimation.SetAnim");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AppendAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			SPRITE_FRAME[] arg0 = ToLua.CheckStructArray<SPRITE_FRAME>(L, 2);
			obj.AppendAnim(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCurrentFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetCurrentFrame(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetPosition(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetClipPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetClipPosition(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLength(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			float o = obj.GetLength();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDuration(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			float o = obj.GetDuration();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFrameCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int o = obj.GetFrameCount();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFramesDisplayed(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int o = obj.GetFramesDisplayed();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCurPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UVAnimation obj = (UVAnimation)ToLua.CheckObject<UVAnimation>(L, 1);
			int o = obj.GetCurPosition();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loopCycles(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int ret = obj.loopCycles;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopCycles on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loopReverse(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			bool ret = obj.loopReverse;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopReverse on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_framerate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			float ret = obj.framerate;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index framerate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int ret = obj.index;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onAnimEnd(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			UVAnimation.ANIM_END_ACTION ret = obj.onAnimEnd;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onAnimEnd on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StepDirection(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int ret = obj.StepDirection;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index StepDirection on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loopCycles(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.loopCycles = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopCycles on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loopReverse(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.loopReverse = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loopReverse on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_framerate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.framerate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index framerate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_index(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.index = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index index on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onAnimEnd(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			UVAnimation.ANIM_END_ACTION arg0 = (UVAnimation.ANIM_END_ACTION)ToLua.CheckObject(L, 2, typeof(UVAnimation.ANIM_END_ACTION));
			obj.onAnimEnd = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onAnimEnd on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_StepDirection(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UVAnimation obj = (UVAnimation)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.StepDirection = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index StepDirection on a nil value");
		}
	}
}

