//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WndFormWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WndForm), typeof(System.Object));
		L.RegFunction("IsQuitApp", IsQuitApp);
		L.RegFunction("WaitQuitApp", WaitQuitApp);
		L.RegFunction("QuitApp", QuitApp);
		L.RegFunction("AddReadyEvent", AddReadyEvent);
		L.RegFunction("CreateWndForm", CreateWndForm);
		L.RegFunction("CreateWndFormAsync", CreateWndFormAsync);
		L.RegFunction("AfterCreate", AfterCreate);
		L.RegFunction("UpdateOrder", UpdateOrder);
		L.RegFunction("TopNode", TopNode);
		L.RegFunction("RemoveNode", RemoveNode);
		L.RegFunction("GetWndID", GetWndID);
		L.RegFunction("InitComponents", InitComponents);
		L.RegFunction("PostDestroySweep", PostDestroySweep);
		L.RegFunction("Create", Create);
		L.RegFunction("Update", Update);
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("ProcessKeyClick", ProcessKeyClick);
		L.RegFunction("Find", Find);
		L.RegFunction("SetTop", SetTop);
		L.RegFunction("SetFocus", SetFocus);
		L.RegFunction("IsShow", IsShow);
		L.RegFunction("SetShow", SetShow);
		L.RegFunction("IsActive", IsActive);
		L.RegFunction("SetFadeIn", SetFadeIn);
		L.RegFunction("SetFadeOut", SetFadeOut);
		L.RegFunction("PostDestroy", PostDestroy);
		L.RegFunction("SetPos", SetPos);
		L.RegFunction("SetDeltaXY", SetDeltaXY);
		L.RegFunction("SetSortingLayer", SetSortingLayer);
		L.RegFunction("Lock", Lock);
		L.RegFunction("Unlock", Unlock);
		L.RegFunction("GetLock", GetLock);
		L.RegFunction("GetPrefab", GetPrefab);
		L.RegFunction("GetBundle", GetBundle);
		L.RegFunction("IsPrefabInResource", IsPrefabInResource);
		L.RegFunction("OnGUIPop", OnGUIPop);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("CFadeOut", 0.5);
		L.RegVar("wID", get_wID, null);
		L.RegVar("isDone", get_isDone, null);
		L.RegVar("parent", get_parent, null);
		L.RegVar("cacheTransform", get_cacheTransform, null);
		L.RegVar("isDestroy", get_isDestroy, null);
		L.RegVar("isFadeOut", get_isFadeOut, null);
		L.RegVar("curAlpha", get_curAlpha, set_curAlpha);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsQuitApp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = WndForm.IsQuitApp();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WaitQuitApp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = WndForm.WaitQuitApp();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int QuitApp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			WndForm.QuitApp();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddReadyEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			IWndFormReady arg0 = (IWndFormReady)ToLua.CheckObject<IWndFormReady>(L, 2);
			obj.AddReadyEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateWndForm(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
				uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				WndForm o = obj.CreateWndForm(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
				uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
				System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				WndForm o = obj.CreateWndForm(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: WndForm.CreateWndForm");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateWndFormAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 6);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			WndForm arg0 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			uint arg2 = (uint)LuaDLL.luaL_checknumber(L, 4);
			System.Collections.ArrayList arg3 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 5);
			bool arg4 = LuaDLL.luaL_checkboolean(L, 6);
			obj.CreateWndFormAsync(arg0, arg1, arg2, arg3, arg4);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AfterCreate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			System.Collections.ArrayList arg0 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 2);
			obj.AfterCreate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateOrder(ref arg0);
			LuaDLL.lua_pushinteger(L, arg0);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TopNode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			WndFormNode arg0 = (WndFormNode)ToLua.CheckObject<WndFormNode>(L, 2);
			obj.TopNode(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveNode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			WndFormNode arg0 = (WndFormNode)ToLua.CheckObject<WndFormNode>(L, 2);
			obj.RemoveNode(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWndID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			uint o = obj.GetWndID();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitComponents(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			WndForm arg1 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			WndForm.InitComponents(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PostDestroySweep(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			WndForm.PostDestroySweep();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			WndForm arg1 = (WndForm)ToLua.CheckObject<WndForm>(L, 3);
			WndFormNode arg2 = (WndFormNode)ToLua.CheckObject<WndFormNode>(L, 4);
			System.Collections.ArrayList arg3 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 5);
			bool o = obj.Create(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.Destroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessKeyClick(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				bool o = obj.ProcessKeyClick(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				UnityEngine.EventType arg1 = (UnityEngine.EventType)ToLua.CheckObject(L, 3, typeof(UnityEngine.EventType));
				bool o = obj.ProcessKeyClick(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 4)
			{
				WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
				UnityEngine.KeyCode arg0 = (UnityEngine.KeyCode)ToLua.CheckObject(L, 2, typeof(UnityEngine.KeyCode));
				UnityEngine.EventType arg1 = (UnityEngine.EventType)ToLua.CheckObject(L, 3, typeof(UnityEngine.EventType));
				bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
				bool o = obj.ProcessKeyClick(arg0, arg1, arg2);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: WndForm.ProcessKeyClick");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Find(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.Find(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetTop(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFocus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.SetFocus();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsShow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool o = obj.IsShow();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetShow(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsActive(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool o = obj.IsActive();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFadeIn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetFadeIn(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetFadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.SetFadeOut(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PostDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.PostDestroy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPos(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.SetPos(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDeltaXY(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.SetDeltaXY(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSortingLayer(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSortingLayer(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.Lock();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Unlock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.Unlock();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool o = obj.GetLock();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPrefab(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
			string o = obj.GetPrefab(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBundle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			System.Collections.ArrayList arg1 = (System.Collections.ArrayList)ToLua.CheckObject<System.Collections.ArrayList>(L, 3);
			string arg2 = null;
			string arg3 = null;
			obj.GetBundle(arg0, arg1, out arg2, out arg3);
			LuaDLL.lua_pushstring(L, arg2);
			LuaDLL.lua_pushstring(L, arg3);
			return 2;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsPrefabInResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			bool o = obj.IsPrefabInResource();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGUIPop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WndForm obj = (WndForm)ToLua.CheckObject<WndForm>(L, 1);
			obj.OnGUIPop();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_wID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			uint ret = obj.wID;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index wID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isDone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			bool ret = obj.isDone;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isDone on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_parent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			WndForm ret = obj.parent;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index parent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cacheTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			UnityEngine.RectTransform ret = obj.cacheTransform;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cacheTransform on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isDestroy(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			bool ret = obj.isDestroy;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isDestroy on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isFadeOut(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			bool ret = obj.isFadeOut;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isFadeOut on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curAlpha(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			float ret = obj.curAlpha;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curAlpha on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curAlpha(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndForm obj = (WndForm)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.curAlpha = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curAlpha on a nil value");
		}
	}
}

