//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WndParticleWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WndParticle), typeof(IWndComponent));
		L.RegFunction("InitComponent", InitComponent);
		L.RegFunction("DinitComponent", DinitComponent);
		L.RegFunction("ChangeParticle", ChangeParticle);
		L.RegFunction("ResetStartOrder", ResetStartOrder);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("iStartLayer", get_iStartLayer, set_iStartLayer);
		L.RegVar("iMaxLayer", get_iMaxLayer, set_iMaxLayer);
		L.RegVar("sAssetName", get_sAssetName, set_sAssetName);
		L.RegVar("sLuaPropertyName", get_sLuaPropertyName, set_sLuaPropertyName);
		L.RegVar("sLuaCallbackName", get_sLuaCallbackName, set_sLuaCallbackName);
		L.RegVar("iChoose", get_iChoose, set_iChoose);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndParticle obj = (WndParticle)ToLua.CheckObject<WndParticle>(L, 1);
			WndForm arg0 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			obj.InitComponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DinitComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndParticle obj = (WndParticle)ToLua.CheckObject<WndParticle>(L, 1);
			WndForm arg0 = (WndForm)ToLua.CheckObject<WndForm>(L, 2);
			obj.DinitComponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeParticle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndParticle obj = (WndParticle)ToLua.CheckObject<WndParticle>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ChangeParticle(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetStartOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WndParticle obj = (WndParticle)ToLua.CheckObject<WndParticle>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.ResetStartOrder(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_iStartLayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int ret = obj.iStartLayer;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iStartLayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_iMaxLayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int ret = obj.iMaxLayer;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iMaxLayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sAssetName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string ret = obj.sAssetName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sAssetName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sLuaPropertyName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string ret = obj.sLuaPropertyName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sLuaPropertyName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sLuaCallbackName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string ret = obj.sLuaCallbackName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sLuaCallbackName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_iChoose(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int ret = obj.iChoose;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iChoose on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_iStartLayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.iStartLayer = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iStartLayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_iMaxLayer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.iMaxLayer = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iMaxLayer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sAssetName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.sAssetName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sAssetName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sLuaPropertyName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.sLuaPropertyName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sLuaPropertyName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sLuaCallbackName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.sLuaCallbackName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sLuaCallbackName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_iChoose(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WndParticle obj = (WndParticle)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.iChoose = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index iChoose on a nil value");
		}
	}
}

